spring:
  datasource:
    platform: h2
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
  h2:
    console:
      enabled: true
management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
security:
  basic:
    enabled: true
